Add generic rabbitmq source
nrkno/odashboard pull request #14
Opened 2017-12-10 22:26 UTC by oyvindholmstad

2017-12-11 08:32 UTC, wiig-with-a-k requested changes

2017-12-11 08:32 UTC, Erlord commented on src/plugins/sources/rabbitmq/Readme.md
> +To configure a connection with a RabbitMQ-server you need to add a new datasource to the list of datasources in server.js. You need one datasource per queue.
Hmm, hvorfor ligger ikke dette inne by default? Ettersom Azure ligger der?

2017-12-11 08:32 UTC, Erlord commented on src/plugins/sources/rabbitmq/source.js
> +module.exports = JsonEndpointSource;
Litt kjapp copy/paste fra JsonEndpoint?

2017-12-11 09:21 UTC, oyvindholmstad commented on src/plugins/sources/rabbitmq/Readme.md
> +To configure a connection with a RabbitMQ-server you need to add a new datasource to the list of datasources in server.js. You need one datasource per queue.
Fixing.

2017-12-11 09:22 UTC, oyvindholmstad commented on src/plugins/sources/rabbitmq/source.js
> +module.exports = JsonEndpointSource;
Fixing.

2017-12-12 17:25 UTC, wiig-with-a-k approved these changes

2017-12-12 17:25 UTC, merged